### ISSUE TITLE
Other errors retrieving some RSS feeds...

### ISSUE THREAD

**Issue by d0cx** [embolalia/willie#537]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/willie/bot.py", line 731, in call
    exit_code = func(willie, trigger)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/rss.py", line 130, in manage_rss
    bot.memory['rss_manager'].manage_rss(bot, trigger)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/rss.py", line 162, in manage_rss
    if getattr(self, '_rss_' + text[1])(bot, trigger, conn.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/rss.py", line 338, in _rss_fetch
    read_feeds(bot, True)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/rss.py", line 409, in read_feeds
    feed.name, status, fp.version, len(fp.entries)), 'verbose')
  File "/usr/local/lib/python2.7/dist-packages/feedparser.py", line 416, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'version'

Willie v4.4.0 running on python 2.7.3 on Ubuntu 12.04.4

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained, per #818. Closing.
