### ISSUE TITLE
specified key was to long at db.py

### ISSUE THREAD

**Issue by NullBy7e** [embolalia/willie#579]
I installed Willie with setup.py install and I get this when I run it:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/willie/__init__.py", line 37, in run
    p = bot.Willie(config)
ck (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/willie/__init__.py", line 37, in run
    p = bot.Willie(config)
  File "/usr/local/lib/python2.7/dist-packages/willie/bot.py", line 82, in __init__
    self.db.add_table('preferences', ['name'], 'name')
  File "/usr/local/lib/python2.7/dist-packages/willie/db.py", line 237, in add_table
    cursor.execute("CREATE TABLE %s %s;" % (name, cols))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

`Edit by Tyrope: Put the traceback in triple backticks for readability.`

**Comment by embolalia** [comment]
This issue is resolved by the 5.0.0 release.
