### ISSUE TITLE
TypeError: can only concatenate list

### ISSUE THREAD

**Issue by slamanna212** [embolalia/willie#674]
I get this error when i try to use most of the modules, so far it affects weather and the web page modules.

Full Error:
```
TypeError: can only concatenate list (not "unicode") to list (file "/home/TrollOP/willie/willie/db.py", line 582, in _get_one)
```

Traceback:
```

Traceback (most recent call last):
  File "/home/TrollOP/willie/willie/bot.py", line 741, in call
    exit_code = func(willie, trigger)
  File "/home/TrollOP/willie/willie/modules/weather.py", line 135, in weather
    woeid = bot.db.get_channel_value(location, 'woeid')
  File "/home/TrollOP/willie/willie/db.py", line 424, in get_channel_value
    return self.preferences.get(nick, key)
  File "/home/TrollOP/willie/willie/tools.py", line 289, in new
    return old(*args, **kwargs)
  File "/home/TrollOP/willie/willie/db.py", line 639, in get
    return self._get_one(row, columns, key)
  File "/home/TrollOP/willie/willie/db.py", line 582, in _get_one
    raise KeyError(row + ' not in database')
TypeError: can only concatenate list (not "unicode") to list
```

Running ubuntu server 14.04, python 2.7, code pulled from git 12 hours ago

**Comment by embolalia** [comment]
This was obviated by the release of 5.0.
