### ISSUE TITLE
Cyclic import makes willie difficult to import.

### ISSUE THREAD

**Issue by robru** [embolalia/willie#701]
Just playing around with willie for the first time in an interactive session.

```
$ python3
Python 3.4.2 (default, Oct  8 2014, 13:08:17) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import willie.module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/willie/module.py", line 22, in <module>
    import willie.test_tools
  File "/usr/local/lib/python3.4/dist-packages/willie/test_tools.py", line 16, in <module>
    import willie.config
  File "/usr/local/lib/python3.4/dist-packages/willie/config.py", line 52, in <module>
    import willie.bot
  File "/usr/local/lib/python3.4/dist-packages/willie/bot.py", line 31, in <module>
    import willie.module as module
AttributeError: 'module' object has no attribute 'module'
>>> import willie
>>> import willie.bot
>>> import willie.module
>>> willie.module.interval
<function interval at 0x7f1b67aeca60>
```

Seems a bit sloppy with the imports there, traceback indicates that `willie.module` imports `willie.bot`, which itself imports `willie.module` and thus fails because it isn't finished importing yet.

**Comment by elad661** [comment]
You are not meant to import Willie's submodules or willie itself in your
program. Willie is not that kind of package.

-
Sent from my phone, please excuse typos.

Elad Alfassa.

**Comment by TomK32** [comment]
Had the same problem, trying to write a spec with mamba. Here's what worked for me:
```python
import willie.bot
from willie.module import example
```
