### ISSUE TITLE
Traceback feedparser.py

### ISSUE THREAD

**Issue by rinzes** [embolalia/willie#729]
I get the following error:

 File "/usr/lib/python2.7/dist-packages/feedparser.py", line 4005, in parse
    saxparser.parse(source)
  File "/usr/lib/python2.7/dist-packages/drv_libxml2.py", line 176, in parse
    SAXException("Read failed (no details available)"))
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 1873, in fatalError
    raise exc

**Comment by janandjohn3** [comment]
I'm gonna post this on both issues, but the partial tracebacks you have
given us are useless, please post a FULL traceback if you would like a
response.

>

-- 
John Lage

**Comment by rinzes** [comment]
ok.. here is all what I got:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/willie/bot.py", line 212, in _call
    func(self.bot)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/rss.py", line 343, in read_feeds
    fp = feedparser.parse(feed.url, etag=feed.etag, modified=feed.modified)
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 4005, in parse
    saxparser.parse(source)
  File "/usr/lib/python2.7/dist-packages/drv_libxml2.py", line 176, in parse
    SAXException("Read failed (no details available)"))
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 1873, in fatalError
    raise exc
SAXException: Read failed (no details available)

**Comment by walliski** [comment]
Quick Google lead me to RSS feeds, as the feedparser tries to read. Could be wrong URL?
Got any feeds you are using?

**Comment by rinzes** [comment]
Yes I have LOTS of feeds and they are all valid feeds as I checked each one before adding.

**Comment by Vashidu** [comment]
Experiencing the same issue too..

```
Traceback (most recent call last):
  File "/home/fbi/willie/willie/bot.py", line 212, in _call
    func(self.bot)
  File "/home/fbi/willie/willie/modules/rss.py", line 354, in read_feeds
    feed.name, status, fp.version, len(fp.entries))
  File "/usr/local/lib/python2.7/dist-packages/feedparser.py", line 416, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'version'
```

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained, per #818. Closing.
