### ISSUE TITLE
Traceback error willie v5.0

### ISSUE THREAD

**Issue by rinzes** [embolalia/willie#735]
Traceback (most recent call last):
  File "gstock.py", line 13, in <module>
    from willie.module import commands
  File "/usr/lib/python2.7/site-packages/willie/module.py", line 21, in <module>
    import willie.test_tools
  File "/usr/lib/python2.7/site-packages/willie/test_tools.py", line 16, in <module>
    import willie.config
  File "/usr/lib/python2.7/site-packages/willie/config.py", line 51, in <module>
    import willie.bot
  File "/usr/lib/python2.7/site-packages/willie/bot.py", line 31, in <module>
    import willie.module as module
AttributeError: 'module' object has no attribute 'module'

**Comment by tyrope** [comment]
gstock.py isn't part of our code. To help you we'll need to see it.
