### ISSUE TITLE
admin.py commands fail due to bad require_privmsg

### ISSUE THREAD

**Issue by khyperia** [embolalia/willie#756]
On a fresh, latest version willie, no user modules and minimal configuration, running .join/.part/etc fails with the following stack trace:

```
Traceback (most recent call last):
  File "/home/khyperia/src/willie/willie/bot.py", line 638, in call
    exit_code = func(willie, trigger)
  File "/home/khyperia/src/willie/willie/module.py", line 277, in _nop
    bot.say(message)
  File "/home/khyperia/src/willie/willie/bot.py", line 586, in say
    self._bot.msg(self._trigger.sender, string, max_messages)
  File "/home/khyperia/src/willie/willie/irc.py", line 420, in msg
    text = encoded_text.decode('utf-8')
AttributeError: 'function' object has no attribute 'decode'
```

I believe this is due to admin.py referencing require_privmsg as `@willie.module.require_privmsg` without parentheses, which is partially handled below the comment `# Hack to allow decorator without parens` in module.py

However, the original `message` (which is a function, not None) is still passed into bot.say, eventually propagating into `encoded_text.decode('utf-8')` and causing the above error and stack trace.

I believe the solution is changing the `if message:` line (which is in many places in module.py) to correctly handle it being a function as well as it being `None`. I would submit a PR, but I'm not sure if that's actually the solution (or the problem in the first place).

---

```
<khyperia> .version
<khyline> khyperia: Willie v. 5.1.1-git at commit: 86e4a4e0f11dd025b30d612df0c0e70842ffb499
OS/Distro: Arch Linux
Obtained by: git clone
```

**Comment by tyrope** [comment]
Testcase 1: (Command issued via PM)
```
[0646.30] <Tyrope> .part #test
[0646.33] <Tyrope> .join #test
```
(Delay due to it still being in start-up sequence)
```
[0646.46] Willie [willie@dftba.net] has left #test
[0646.46] Willie [willie@dftba.net] has joined #test
```
---
Testcase 2: (Command issued in-channel)
```
[0648.36] <~Tyrope> .part
[0648.36] <@Willie> AttributeError: 'function' object has no attribute 'decode' (file "/home/willie/jenni/willie/irc.py", line 420, in msg)
[0648.40] <~Tyrope> .part #test
[0648.41] <@Willie> AttributeError: 'function' object has no attribute 'decode' (file "/home/willie/jenni/willie/irc.py", line 420, in msg)
```
--
Exceptions.log:
```
Signature: AttributeError: 'function' object has no attribute 'decode' (file     "/home/willie/jenni/willie/irc.py", line 420, in msg)
from Tyrope at 2015-03-05 00:48:52.127515. Message was: .part #test
Traceback (most recent call last):
  File "/home/willie/jenni/willie/bot.py", line 638, in call
    exit_code = func(willie, trigger)
  File "/home/willie/jenni/willie/module.py", line 277, in _nop
    bot.say(message)
  File "/home/willie/jenni/willie/bot.py", line 586, in say
    self._bot.msg(self._trigger.sender, string, max_messages)
  File "/home/willie/jenni/willie/irc.py", line 420, in msg
    text = encoded_text.decode('utf-8')
AttributeError: 'function' object has no attribute 'decode'
```
```
