### ISSUE TITLE
NameError: global name 'Trigger' is not defined

### ISSUE THREAD

**Issue by LittleCerise** [embolalia/willie#767]
Getting lots of these
----------------------------------------
Fatal error in core, handle_error() was called
last raw line was NoneTraceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/asynchat.py", line 158, in handle_read
    self.found_terminator()
  File "/usr/local/lib/python2.7/dist-packages/willie/irc.py", line 390, in found_terminator
    self.dispatch(pretrigger)
  File "/usr/local/lib/python2.7/dist-packages/willie/bot.py", line 666, in dispatch
    trigger = Trigger(self.config, pretrigger, match)
NameError: global name 'Trigger' is not defined
Buffer:
----------------------------------------
Seen others get this but the issues seem to be fixed or closed, not sure why I'm getting it.

**Comment by janandjohn3** [comment]
What version of willie are you running?

**Comment by LittleCerise** [comment]
Willie 5.0.0-beta (running on python 2.7.3)

**Comment by janandjohn3** [comment]
Try using willie 5.2.0 (the latest version) and see if it still produces that error, please.

**Comment by LittleCerise** [comment]
Fixed thanks!
