### ISSUE TITLE
command 'time' commUnknownTimeZoneError

### ISSUE THREAD

**Issue by webgori** [embolalia/willie#772]
```
[14:23] <webgori> .settz Asia/Seoul
[14:23] <Bot-MW_> webgori: Sorry, I don't have timezone support installed.
[14:34] <webgori> .gettz
[14:34] <Bot-MW_> webgori: Sorry, I don't have timezone support installed.

[root@localhost modules]# pip install pytz
Collecting pytz
  Using cached pytz-2015.2-py2.py3-none-any.whl
Installing collected packages: pytz

Successfully installed pytz-2015.2

Welcome to Willie. Loading modules...


Error loading spellcheck: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI. (../enchant/_enchant.py:143)
Error in safety setup procedure: ConfigurationError: Safety module not configured (modules/safety.py:55)


Registered 45 modules,
2 modules failed to load


Connecting to irc.luatic.net:7778...
Connected.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/willie/bot.py", line 639, in call
    exit_code = func(willie, trigger)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 144, in log_join
    logline = _format_template(tpl, bot, trigger)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 87, in _format_template
    dt = get_datetime(bot)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 61, in get_datetime
    dt = dt.astimezone(timezone(bot.config.clock.tz))
  File "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: '+09:00'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/willie/bot.py", line 639, in call
    exit_code = func(willie, trigger)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 132, in log_message
    logline = _format_template(tpl, bot, message, message=message)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 87, in _format_template
    dt = get_datetime(bot)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 61, in get_datetime
    dt = dt.astimezone(timezone(bot.config.clock.tz))
  File "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: '+09:00'


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/willie/bot.py", line 639, in call
    exit_code = func(willie, trigger)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 144, in log_join
    logline = _format_template(tpl, bot, trigger)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 87, in _format_template
    dt = get_datetime(bot)
  File "/usr/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 61, in get_datetime
    dt = dt.astimezone(timezone(bot.config.clock.tz))
  File "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: '+09:00'


[14:36] <Bot-MW_> UnknownTimeZoneError: '+09:00' (file "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 180, in timezone)
[14:36] <Bot-MW_> UnknownTimeZoneError: '+09:00' (file "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 180, in timezone)
```

**Comment by tyrope** [comment]
`dt = dt.astimezone(timezone(bot.config.clock.tz))`
That makes me think your config file's [clock]tz value is set incorrectly.

**Comment by webgori** [comment]
@tyrope delete config file and reconfig ok.
thanks.
