### ISSUE TITLE
CentOS pip install error

### ISSUE THREAD

**Issue by ca1ek** [embolalia/willie#829]
When I try to install Willie using pip I encounter this error:
```
[dawid@ns3287850 ~]$ sudo pip install willie
Downloading/unpacking willie
  Running setup.py egg_info for package willie
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/willie/setup.py", line 18, in <module>
        if sys.version_info.major < 3:
    AttributeError: 'tuple' object has no attribute 'major'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
 
  File "<string>", line 16, in <module>
 
  File "/tmp/pip-build-root/willie/setup.py", line 18, in <module>
 
    if sys.version_info.major < 3:
 
AttributeError: 'tuple' object has no attribute 'major'
 
----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/willie
Storing complete log in /root/.pip/pip.log
```

I use CentOS release 6.5.

**Comment by embolalia** [comment]
CentOS 6 ships with Python 2.6, which Willie does not support. [This page](http://willie.dftba.net/python3-centos7.html) tells you the best way to do Python 3.3 (which Willie does support) on CentOS. Note the footnote for CentOS 6.
